# Generated by Django 6.0.2 on 2026-02-11 18:03

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False),
        ),
    ]
