openapi: 3.0.3
info:
  title: SkillBridge API
  version: 1.0.0
  description: Connect Volunteers with NGOs
paths:
  /api/profile/:
    get:
      operationId: profile_retrieve
      tags:
      - profile
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
    put:
      operationId: profile_update
      tags:
      - profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Profile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Profile'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
    patch:
      operationId: profile_partial_update
      tags:
      - profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProfile'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProfile'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProfile'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
          description: ''
  /api/register/:
    post:
      operationId: register_create
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
components:
  schemas:
    PatchedProfile:
      type: object
      properties:
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        email:
          type: string
          format: email
          readOnly: true
          title: Email address
        full_name:
          type: string
          nullable: true
          maxLength: 255
        role:
          allOf:
          - $ref: '#/components/schemas/RoleEnum'
          readOnly: true
        location:
          type: string
          nullable: true
          maxLength: 255
        organization_name:
          type: string
          nullable: true
          maxLength: 255
        organization_description:
          type: string
          nullable: true
        website_url:
          type: string
          format: uri
          nullable: true
          maxLength: 200
    Profile:
      type: object
      properties:
        username:
          type: string
          readOnly: true
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
        email:
          type: string
          format: email
          readOnly: true
          title: Email address
        full_name:
          type: string
          nullable: true
          maxLength: 255
        role:
          allOf:
          - $ref: '#/components/schemas/RoleEnum'
          readOnly: true
        location:
          type: string
          nullable: true
          maxLength: 255
        organization_name:
          type: string
          nullable: true
          maxLength: 255
        organization_description:
          type: string
          nullable: true
        website_url:
          type: string
          format: uri
          nullable: true
          maxLength: 200
      required:
      - email
      - role
      - username
    Register:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
        full_name:
          type: string
          nullable: true
          maxLength: 255
        role:
          $ref: '#/components/schemas/RoleEnum'
        location:
          type: string
          nullable: true
          maxLength: 255
        organization_name:
          type: string
          nullable: true
          maxLength: 255
        organization_description:
          type: string
          nullable: true
        website_url:
          type: string
          format: uri
          nullable: true
          maxLength: 200
      required:
      - password
      - role
      - username
    RoleEnum:
      enum:
      - Volunteer
      - NGO / Organization
      type: string
      description: |-
        * `Volunteer` - Volunteer
        * `NGO / Organization` - NGO / Organization
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
